// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateFramework struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Version     string   `json:"version"`
	Locked      bool     `json:"locked"`
	Editable    bool     `json:"editable"`
	Category    []string `json:"category"`
}

type DeleteFramework struct {
	ID string `json:"id"`
}

type Framework struct {
	ID          string    `json:"id"`
	Name        *string   `json:"name,omitempty"`
	Description *string   `json:"description,omitempty"`
	Version     *string   `json:"version,omitempty"`
	Locked      *bool     `json:"locked,omitempty"`
	Editable    *bool     `json:"editable,omitempty"`
	Category    []string  `json:"category,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Message struct {
	Msg *string `json:"msg,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateFramework struct {
	ID          string   `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Version     *string  `json:"version,omitempty"`
	Locked      *bool    `json:"locked,omitempty"`
	Editable    *bool    `json:"editable,omitempty"`
	Category    []string `json:"category,omitempty"`
}
