// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Framework struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Version     pgtype.Text
	Locked      bool
	Editable    bool
	Category    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
